// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 0.2.0
// Version Date: 2020-10-24

package main

import (
	"flag"

	// This Service
	"github.com/techxmind/logserver/config"
	"github.com/techxmind/logserver/service/svc/server"
)

var (
	// version is compiled into logservice with the flag
	// go install -ldflags "-X main.version=$VERSION"
	version string

	// BuildDate is compiled into logservice with the flag
	// go install -ldflags "-X main.date=$VERSION_DATE"
	date string
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	config.DefaultConfig.Version = version
	config.DefaultConfig.VersionDate = date

	server.Run(config.DefaultConfig)
}
