// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 0.2.0
// Version Date: 2020-10-24

package main

import (
	"flag"

	// This Service
	"github.com/techxmind/logserver/config"
	"github.com/techxmind/logserver/service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(config.DefaultConfig)
}
