CREATE TABLE event_log (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(32) NOT NULL,
  logged_time timestamp NOT NULL,
  logged_date bigint NOT NULL,
  event_time bigint NOT NULL DEFAULT 0,
  session_id varchar(32) NOT NULL,
  udid varchar(32) NOT NULL DEFAULT '',
  tkid varchar(32) NOT NULL DEFAULT '',
  mid varchar(32) NOT NULL DEFAULT '',
  platform varchar(10) NOT NULL DEFAULT '',
  app_version varchar(10) NOT NULL DEFAULT '',
  app_channel varchar(50) NOT NULL DEFAULT '',
  app_type varchar(20) NOT NULL DEFAULT '',
  user_agent varchar(100) NOT NULL DEFAULT '',
  event varchar(20) NOT NULL DEFAULT '',
  env varchar(10) NOT NULL DEFAULT '',
  os varchar(10) NOT NULL DEFAULT '',
  os_version varchar(15) NOT NULL DEFAULT '',
  device_model varchar(20) NOT NULL DEFAULT '',
  device_vendor varchar(20) NOT NULL DEFAULT '',
  device_brand varchar(20) NOT NULL DEFAULT '',
  screen_size varchar(10) not null default 0,
  screen_height int not null default 0,
  screen_width int not null default 0,
  screen_resolution varchar(10) not null default '',
  imei varchar(32) not null default '',
  android_id varchar(32) not null default '',
  idfa varchar(32) not null default '',
  oaid varchar(32) not null default '',
  carrier int not null default 0,
  network int not null default 0,
  ip varchar(15) not null default '',
  ip_country varchar(20) not null default '',
  ip_province varchar(20) not null default '',
  ip_city varchar(20) not null default '',
  lon varchar(15) not null default '',
  lat varchar(15) not null default '',
  mac varchar(32) not null default '',
  page_id varchar(50) not null default '',
  pv_id varchar(50) not null default '',
  layout_id varchar(50) not null default '',
  page_key varchar(50) not null default '',
  module_id varchar(50) not null default '',
  action_type varchar(20) not null default '',
  ref_page_id varchar(50) not null default '',
  ref_pv_id varchar(50) not null default '',
  ref_layout_id varchar(50) not null default '',
  ref_module_id varchar(50) not null default '',
  referer varchar(250) not null default '',
  duration int not null default 0,
  extend_info JSON NULL,
  UNIQUE KEY(event_id),
  KEY(logged_time),
  KEY(logged_date),
  KEY(mid),
  KEY(ip),
  KEY(udid),
  KEY(event)
) engine=InnoDB default CHARSET utf8mb4;
