// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 0.2.0
// Version Date: 2020-10-24

// Package http provides an HTTP client for the LogService service.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/gogo/protobuf/jsonpb"

	"github.com/go-kit/kit/endpoint"
	httptransport "github.com/go-kit/kit/transport/http"
	"github.com/pkg/errors"

	// This Service
	pb "github.com/techxmind/logserver/interface-defs"
	"github.com/techxmind/logserver/service/svc"
)

var (
	_ = endpoint.Chain
	_ = httptransport.NewClient
	_ = fmt.Sprint
	_ = bytes.Compare
	_ = ioutil.NopCloser
)

// New returns a service backed by an HTTP server living at the remote
// instance. We expect instance to come from a service discovery system, so
// likely of the form "host:port".
func New(instance string, options ...httptransport.ClientOption) (pb.LogServiceServer, error) {

	if !strings.HasPrefix(instance, "http") {
		instance = "http://" + instance
	}
	u, err := url.Parse(instance)
	if err != nil {
		return nil, err
	}
	_ = u

	var SubmitSingleZeroEndpoint endpoint.Endpoint
	{
		SubmitSingleZeroEndpoint = httptransport.NewClient(
			"POST",
			copyURL(u, "/s"),
			EncodeHTTPSubmitSingleZeroRequest,
			DecodeHTTPSubmitSingleResponse,
			options...,
		).Endpoint()
	}
	var SubmitMultipleZeroEndpoint endpoint.Endpoint
	{
		SubmitMultipleZeroEndpoint = httptransport.NewClient(
			"POST",
			copyURL(u, "/mul"),
			EncodeHTTPSubmitMultipleZeroRequest,
			DecodeHTTPSubmitMultipleResponse,
			options...,
		).Endpoint()
	}
	var PingZeroEndpoint endpoint.Endpoint
	{
		PingZeroEndpoint = httptransport.NewClient(
			"GET",
			copyURL(u, "/ping"),
			EncodeHTTPPingZeroRequest,
			DecodeHTTPPingResponse,
			options...,
		).Endpoint()
	}

	return svc.Endpoints{
		SubmitSingleEndpoint:   SubmitSingleZeroEndpoint,
		SubmitMultipleEndpoint: SubmitMultipleZeroEndpoint,
		PingEndpoint:           PingZeroEndpoint,
	}, nil
}

func copyURL(base *url.URL, path string) *url.URL {
	next := *base
	next.Path = path
	return &next
}

// CtxValuesToSend configures the http client to pull the specified keys out of
// the context and add them to the http request as headers.  Note that keys
// will have net/http.CanonicalHeaderKey called on them before being send over
// the wire and that is the form they will be available in the server context.
func CtxValuesToSend(keys ...string) httptransport.ClientOption {
	return httptransport.ClientBefore(func(ctx context.Context, r *http.Request) context.Context {
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				r.Header.Set(k, v)
			}
		}
		return ctx
	})
}

// HTTP Client Decode

// DecodeHTTPSubmitSingleResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded Response response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPSubmitSingleResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.Response
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// DecodeHTTPSubmitMultipleResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded Response response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPSubmitMultipleResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.Response
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// DecodeHTTPPingResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded Response response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPPingResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.Response
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// HTTP Client Encode

// EncodeHTTPSubmitSingleZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a submitsingle request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSubmitSingleZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.EventLog)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"s",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.EventLog)

	toRet.EventId = req.EventId

	toRet.EventTime = req.EventTime

	toRet.LoggedTime = req.LoggedTime

	toRet.SessionId = req.SessionId

	toRet.Udid = req.Udid

	toRet.Tkid = req.Tkid

	toRet.Mid = req.Mid

	toRet.Platform = req.Platform

	toRet.AppVersion = req.AppVersion

	toRet.AppChannel = req.AppChannel

	toRet.AppType = req.AppType

	toRet.UserAgent = req.UserAgent

	toRet.Event = req.Event

	toRet.Env = req.Env

	toRet.Os = req.Os

	toRet.OsVersion = req.OsVersion

	toRet.DeviceModel = req.DeviceModel

	toRet.DeviceVendor = req.DeviceVendor

	toRet.DeviceBrand = req.DeviceBrand

	toRet.ScreenSize = req.ScreenSize

	toRet.ScreenWidth = req.ScreenWidth

	toRet.ScreenHeight = req.ScreenHeight

	toRet.ScreenResolution = req.ScreenResolution

	toRet.Imei = req.Imei

	toRet.AndroidId = req.AndroidId

	toRet.Idfa = req.Idfa

	toRet.Oaid = req.Oaid

	toRet.Carrier = req.Carrier

	toRet.Network = req.Network

	toRet.Ip = req.Ip

	toRet.IpCountry = req.IpCountry

	toRet.IpProvince = req.IpProvince

	toRet.IpCity = req.IpCity

	toRet.Lon = req.Lon

	toRet.Lat = req.Lat

	toRet.Mac = req.Mac

	toRet.PageId = req.PageId

	toRet.PvId = req.PvId

	toRet.LayoutId = req.LayoutId

	toRet.PageKey = req.PageKey

	toRet.ModuleId = req.ModuleId

	toRet.ActionType = req.ActionType

	toRet.RefPageId = req.RefPageId

	toRet.RefPvId = req.RefPvId

	toRet.RefLayoutId = req.RefLayoutId

	toRet.RefPageKey = req.RefPageKey

	toRet.RefModuleId = req.RefModuleId

	toRet.Referer = req.Referer

	toRet.Duration = req.Duration

	toRet.ExtendInfo = req.ExtendInfo

	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPSubmitMultipleZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a submitmultiple request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSubmitMultipleZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.EventLogs)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"mul",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.EventLogs)

	toRet.Common = req.Common

	toRet.Events = req.Events

	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPPingZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a ping request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPPingZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.Empty)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"ping",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	r.URL.RawQuery = values.Encode()
	return nil
}

func errorDecoder(buf []byte) error {
	var w errorWrapper
	if err := json.Unmarshal(buf, &w); err != nil {
		const size = 8196
		if len(buf) > size {
			buf = buf[:size]
		}
		return fmt.Errorf("response body '%s': cannot parse non-json request body", buf)
	}

	return errors.New(w.Error)
}

type errorWrapper struct {
	Error string `json:"error"`
}
