// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 0.2.0
// Version Date: 2020-10-24

// Package grpc provides a gRPC client for the LogService service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/techxmind/logserver/interface-defs"
	"github.com/techxmind/logserver/service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.LogServiceServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var submitsingleEndpoint endpoint.Endpoint
	{
		submitsingleEndpoint = grpctransport.NewClient(
			conn,
			"event_log.LogService",
			"SubmitSingle",
			EncodeGRPCSubmitSingleRequest,
			DecodeGRPCSubmitSingleResponse,
			pb.Response{},
			clientOptions...,
		).Endpoint()
	}

	var submitmultipleEndpoint endpoint.Endpoint
	{
		submitmultipleEndpoint = grpctransport.NewClient(
			conn,
			"event_log.LogService",
			"SubmitMultiple",
			EncodeGRPCSubmitMultipleRequest,
			DecodeGRPCSubmitMultipleResponse,
			pb.Response{},
			clientOptions...,
		).Endpoint()
	}

	var pingEndpoint endpoint.Endpoint
	{
		pingEndpoint = grpctransport.NewClient(
			conn,
			"event_log.LogService",
			"Ping",
			EncodeGRPCPingRequest,
			DecodeGRPCPingResponse,
			pb.Response{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		SubmitSingleEndpoint:   submitsingleEndpoint,
		SubmitMultipleEndpoint: submitmultipleEndpoint,
		PingEndpoint:           pingEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCSubmitSingleResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC submitsingle reply to a user-domain submitsingle response. Primarily useful in a client.
func DecodeGRPCSubmitSingleResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Response)
	return reply, nil
}

// DecodeGRPCSubmitMultipleResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC submitmultiple reply to a user-domain submitmultiple response. Primarily useful in a client.
func DecodeGRPCSubmitMultipleResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Response)
	return reply, nil
}

// DecodeGRPCPingResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC ping reply to a user-domain ping response. Primarily useful in a client.
func DecodeGRPCPingResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Response)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCSubmitSingleRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain submitsingle request to a gRPC submitsingle request. Primarily useful in a client.
func EncodeGRPCSubmitSingleRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.EventLog)
	return req, nil
}

// EncodeGRPCSubmitMultipleRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain submitmultiple request to a gRPC submitmultiple request. Primarily useful in a client.
func EncodeGRPCSubmitMultipleRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.EventLogs)
	return req, nil
}

// EncodeGRPCPingRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain ping request to a gRPC ping request. Primarily useful in a client.
func EncodeGRPCPingRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Empty)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
