// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 0.2.0
// Version Date: 2020-10-24

package server

import (
	"log"
	"net"
	"net/http"
	"net/http/pprof"

	// 3d Party
	"google.golang.org/grpc"

	// This Service
	"github.com/techxmind/logserver/config"
	pb "github.com/techxmind/logserver/interface-defs"
	"github.com/techxmind/logserver/service/handlers"
	"github.com/techxmind/logserver/service/svc"
)

func NewEndpoints(service pb.LogServiceServer) svc.Endpoints {
	// Business domain.

	// Wrap Service with middlewares. See handlers/middlewares.go
	service = handlers.WrapService(service)

	// Endpoint domain.
	var (
		submitsingleEndpoint   = svc.MakeSubmitSingleEndpoint(service)
		submitmultipleEndpoint = svc.MakeSubmitMultipleEndpoint(service)
		pingEndpoint           = svc.MakePingEndpoint(service)
	)

	endpoints := svc.Endpoints{
		SubmitSingleEndpoint:   submitsingleEndpoint,
		SubmitMultipleEndpoint: submitmultipleEndpoint,
		PingEndpoint:           pingEndpoint,
	}

	// Wrap selected Endpoints with middlewares. See handlers/middlewares.go
	endpoints = handlers.WrapEndpoints(endpoints)

	return endpoints
}

// Run starts a new http server, gRPC server, and a debug server with the
// passed config and logger
func Run(cfg *config.Config) {
	service := handlers.NewService()
	endpoints := NewEndpoints(service)

	// Mechanical domain.
	errc := make(chan error)

	// Interrupt handler.
	go handlers.InterruptHandler(errc)

	// Debug listener.
	go func() {
		log.Println("transport", "debug", "addr", cfg.DebugAddr)

		m := http.NewServeMux()
		m.Handle("/debug/pprof/", http.HandlerFunc(pprof.Index))
		m.Handle("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
		m.Handle("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
		m.Handle("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
		m.Handle("/debug/pprof/trace", http.HandlerFunc(pprof.Trace))

		handlers.WrapDebugService(m)

		errc <- http.ListenAndServe(cfg.DebugAddr, m)
	}()

	// HTTP transport.
	go func() {
		log.Println("transport", "HTTP", "addr", cfg.HTTPAddr)
		h := svc.MakeHTTPHandler(endpoints)
		errc <- http.ListenAndServe(cfg.HTTPAddr, h)
	}()

	// gRPC transport.
	go func() {
		log.Println("transport", "gRPC", "addr", cfg.GRPCAddr)
		ln, err := net.Listen("tcp", cfg.GRPCAddr)
		if err != nil {
			errc <- err
			return
		}

		srv := svc.MakeGRPCServer(endpoints)
		s := grpc.NewServer()
		pb.RegisterLogServiceServer(s, srv)

		errc <- s.Serve(ln)
	}()

	// Run!
	log.Println("exit", <-errc)
}
